### ISSUE TITLE
Support downlink

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/integration-azure#15]
Fairly easy; https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

**Comment by johanstokking** [comment]
@sandervandevelde what is your use case exactly?

**Comment by sandervandevelde** [comment]
We try to test downlink using the Device Explorer for IoT Hub. We see the downlink arrive at TTN console portal but message body is empty. Will investigate further with example above..

**Comment by johanstokking** [comment]
It is not supported by this bridge, but it seems easy to implement. I'll look tomorrow.
