### ISSUE TITLE
Azure IoT Edge & Azure Functions

### ISSUE THREAD

**Issue by grahamehorner** [TheThingsNetwork/integration-azure#19]
Please consider integration with Azure IoT Edge as a module; this allow the ability to ingest LoRaWan message perform stream analytics, machine learning on the data at the network edge/gateway prior to sending to the cloud or over a network that may be low bandwidth/costly

**Comment by johanstokking** [comment]
Gateway will not work as it's fully transparent, but I do see this working in an integration on the Application Server indeed.

I keep this one open until we release V3.

**Comment by grahamehorner** [comment]
I've just received a replacement gateway from rish for the original DEAD gateway, which I've been able to connection first time :D   I'm interested in the idea of azure integrations, thing along the lines of an Azure Functions MQTT/AMQP listener trigger version of your bridge

**Comment by htdvisser** [comment]
With The Things Network V2 shut down, we're going archive this repository, so this issue will be locked.
