### ISSUE TITLE
Update for production

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/integration-azure#2]
Currently based on staging.

**Comment by johanstokking** [comment]
What's the status on this regarding #4 ?

**Comment by FokkeZB** [comment]
Well, that is based on production:

- https://github.com/TheThingsNetwork/azure-app-lib/blob/master/package.json#L24
- https://github.com/TheThingsNetwork/azure-app-lib/blob/master/index.js#L15

So we can close this issue.
