### ISSUE TITLE
RFC: Rename to azure-integration-lib

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/integration-azure#6]
Because that's what it is.

**Comment by FokkeZB** [comment]
Agree. How about `lib`? The others like `node-app-lib` will be renamed to `node-app-sdk`. For an integration that doesn't really make sense but maybe we should just drop `-lib` and go with `azure-integration`?

**Comment by johanstokking** [comment]
Yes that's right

**Comment by FokkeZB** [comment]
I assume we won't rename the package name (`ttn-azure-iothub`)?

**Comment by johanstokking** [comment]
The package name is fine indeed

**Comment by johanstokking** [comment]
Closed by #7
